"""changed password to not unique

Revision ID: 2436a6acc342
Revises: 2ad934f32a18
Create Date: 2024-11-10 15:02:53.347707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2436a6acc342'
down_revision = '2ad934f32a18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('password', ['password'], unique=True)

    # ### end Alembic commands ###
