"""removed family_id from task

Revision ID: 47edd7d1f8f7
Revises: 69da61bfda97
Create Date: 2024-11-13 07:28:01.091294

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '47edd7d1f8f7'
down_revision = '69da61bfda97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('tasks_ibfk_1', type_='foreignkey')
        batch_op.drop_column('family_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('tasks_ibfk_1', 'family', ['family_id'], ['id'])

    # ### end Alembic commands ###
