"""removed task_id

Revision ID: 69da61bfda97
Revises: a509e5a20875
Create Date: 2024-11-12 23:44:49.939881

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '69da61bfda97'
down_revision = 'a509e5a20875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint('notifications_ibfk_1', type_='foreignkey')
        batch_op.drop_column('task_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('notifications_ibfk_1', 'tasks', ['task_id'], ['id'])

    # ### end Alembic commands ###
